client/package-lock.json, client/package.json, client/public/index.html, client/src/App.js, client/src/Landing.jsx, client/src/components/Button.jsx, client/src/components/Header.jsx, client/src/index.js, client/src/pages/Home.jsx, client/src/pages/Landing.jsx
Additional setup to the project like installing react router and importing it, reformatting files, creating a directory for page components, and creating an indigo-themed landing page. Also added some global styling. Clicking the Go button in the landing page takes the user to a Home page with just a heading for now.
=> Setup landing

client/src/App.js, client/src/api/index.js, client/src/pages/Home.jsx, server/routes/albums.js, server/routes/artists.js, server/routes/chartYear.js
Added API routes to retrieve the Chart, Artists, and Albums collections as well as route params for Albums and Artists API calls.
=> Finish api routing

client/package-lock.json, client/src/api/index.js, package-lock.json, server/index.js, server/models/Genres.js, server/routes/albums.js, server/routes/artists.js, server/routes/chartYear.js, server/routes/genres.js
Added genre routes to server, cleaned up api code in client, tested routes on the server
=> added genre/chart year route params

client/src/App.js, client/src/components/Navbar.jsx, client/src/components/Question.jsx, client/src/components/TeamProfile.jsx, client/src/components/questions.js, client/src/components/team.js, client/src/pages/About.jsx, client/src/pages/Genres.jsx, client/src/pages/Home.jsx, server/index.js
Linked appropriate pages in nav bar, added Question + TeamProfile components + About.jsx page
=> About page

client/src/App.js, client/src/api/index.js, client/src/components/AlbumModal.jsx, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualArtist.jsx
Added individual artist and individual album page. Created AlbumModal.jsx component that renders an individual artist page and links to the individual
=> Individual artist

client/src/components/ArtistsThumb.jsx, client/src/components/ArtistsThumbImg.jsx, client/src/pages/Artists.jsx, server/routes/artists.js
I added images to the artists-page. I did this by creating separate components for the image and fetching the image using the artist name with the AudioDB API.
=> added images to artists-page

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/ArtistBio.jsx, client/src/components/ArtistsThumbImg.jsx, client/src/pages/IndividualArtist.jsx
fixed some styling on artist pages.
=> Artists page

client/package-lock.json, client/package.json, client/public/index.html, client/src/App.js, client/src/api/index.js, client/src/components/AlbumSnapshot.jsx, client/src/components/ArtistsThumb.jsx, client/src/components/ChartPosRecap.jsx, client/src/components/Dropdown.jsx, client/src/components/Entry.jsx, client/src/components/GenrePie.jsx, client/src/components/GrammyRecap.jsx, client/src/components/SpotifyWidget.jsx, client/src/pages/Home.jsx, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualArtist.jsx, client/src/pages/IndividualGenre.jsx, client/tailwind.config.js, server/index.js, server/package-lock.json, server/package.json, server/routes/artists.js
Incorporated spotify widget, modularized the Individual Album page, edited some route formatting
=> Spotify integrate

client/src/components/AlbumSnapshot.jsx, client/src/components/ArtistBio.jsx, client/src/components/ArtistsThumb.jsx, client/src/components/team.js, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualArtist.jsx
I added a toggle button to the album page for the biography, as well as fixed the description style for this page and the artist biography style.
=> tweaks to individual artist and album pages

client/src/components/GenreThumb.jsx, client/src/pages/Genres.jsx
Responsive circles for genres page
=> genres page circles updated

client/src/components/ArtistsThumb.jsx, client/src/components/ArtistsThumbImg.jsx, client/src/components/ChartPosRecap.jsx, client/src/pages/Artists.jsx, client/src/pages/IndividualArtist.jsx
I linked the album page as well as performed some stylistic changes on the artists page.
=> minor tweaks on linking album page

client/src/components/GenreOverTime.jsx, client/src/components/GenrePie.jsx, client/src/pages/Home.jsx, client/src/pages/IndividualGenre.jsx, server/routes/albums.js
created a new graph for the genre page and styled and tweaked axis labels for line graph
=> formatted linegraph axes

client/src/components/AlbumSnapshot.jsx, client/src/components/ArtistBio.jsx, client/src/pages/IndividualArtist.jsx, client/src/pages/IndividualGenre.jsx
I fixed the "More" and "Less" button styling and individual artist page styling.
=> artist-tweaks on styling and others

client/src/components/ArtistBio.jsx, client/src/components/ArtistsThumb.jsx, client/src/components/ArtistsThumbImg.jsx, client/src/pages/Artists.jsx, client/src/pages/Genres.jsx, client/src/pages/IndividualGenre.jsx
I fixed the artists page so the placeholder could be aesthetically pleasing. Fixed the description div in individual genre page to cut text out evenly.
=> added artists page placeholder and fixed ind_genre styling

client/src/components/AlbumSnapshot.jsx, client/src/components/ArtistBio.jsx, client/src/components/LoadingRing.jsx, client/src/pages/IndividualArtist.jsx
created LoadingRing component and changed album bio to show "No bio available" when API doesn't return a biography
=> added loading SVG to artist bio + small styling

client/src/components/AlbumSnapshot.jsx, client/src/components/ChartPosRecap.jsx, client/src/components/GrammyComponent.jsx, client/src/components/GrammyRecap.jsx, client/src/components/SpotifyWidget.jsx, client/src/pages/IndividualAlbum.jsx
- Replaced GrammyRecap component with Tooltip component to save screen real estate.
- Implemented custom styled material-ui Badge component
=> Replace album image

client/src/api/index.js, client/src/components/ArtistsThumb.jsx, client/src/components/ArtistsThumbImg.jsx, client/src/pages/Artists.jsx, server/routes/artists.js
Added a nav bar in artists page to be able to surf through the page with the artists' first letter of their name. Fixed fade-in styling on the page as well.
=> added navigational alphabet to artists

client/src/App.js, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualArtist.jsx, client/src/pages/IndividualGenre.jsx
User is redirected anytime they visit a path that doesn't return a relevant resource in the database
=> handled rerouting on all paths

client/src/components/SearchBar.jsx, client/src/pages/Artists.jsx, client/src/pages/Genres.jsx, client/tailwind.config.js
This branch connects Artists and Genres pages with a filtered search-bar. Users can type in letters in the searchbar and results corresponding to their search will appear.
=> Filter search

client/package-lock.json, client/src/components/ArtistCircleImg.jsx, client/src/components/ArtistsThumb.jsx, client/src/pages/Artists.jsx, client/src/pages/IndividualArtist.jsx
I created a separate component to deal with the general artists' images and the individual artist images. I also fixed the navbar to be more aesthetically pleasing and functional.
=> fixed alphabetical navbar and artists images

client/src/App.js, client/src/components/AlbumSnapshot.jsx, client/src/components/SpotifyWidget.jsx, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualGenre.jsx
-Edited AlbumSnapshot component to not have ChartPosRecap component as child
-Added global padding to website to accomodate player height at the bottom of the screen
-Added track listing to each IndividualAlbum page
=> Album page styling/tracks

client/src/App.js, client/src/components/ArtistsThumbnail.jsx, client/src/components/Navbar.jsx, client/src/pages/About.jsx, client/src/pages/Artists.jsx, client/src/pages/Genres.jsx, client/src/pages/Home.jsx, client/src/pages/IndividualArtist.jsx
I rerouted the artists so when the user clicks a letter in the alphabetical navbar it reroutes to a different URL. This way when the user refreshes or clicks back from going to a certain artist, he can stay on the letter he was originally on.
=> rerouted artists

client/src/App.js, client/src/components/ArtistCircleImg.jsx, client/src/components/ArtistsThumbnail.jsx, client/src/components/GenrePie.jsx, client/src/pages/Artists.jsx, client/src/pages/IndividualAlbum.jsx, client/src/pages/IndividualArtist.jsx, server/index.js
Changes: 
- All artist objects in DB now have images. 
- Removed extraneous calls to Spotify API in ArtistsThumbnail and ArtistCircleImg components + passed appropriate props to access new image field in Artist object.
- Removed setTimeout method in Artists.jsx page since we're not getting rate limited anymore
=> Db artist img

client/src/components/AlbumSnapshot.jsx, client/src/pages/Artists.jsx
I added a numerical navbar to the artists page and fixed a couple of routes for direction to the individual artist page.
=> Added numerical navbar to artists and redirected some routes

client/src/api/index.js, client/src/components/AlbumSuggestions.jsx, client/src/components/SuggestedList.jsx, client/src/components/searchBox.jsx, server/routes/albums.js
=> Checkbox added

client/src/api/index.js, client/src/components/AlbumSnapshot.jsx, client/src/pages/IndividualAlbum.jsx, server/index.js, server/routes/spotify.js
Minor tweaks:
- Removed route that revealed access token on the backend
- Moved all Spotify calls/responses in the backend
- Error checking to ensure that if no Spotify album is found, no track list or button is rendered.
=> Spotify routing
